# codemagic.yaml
workflows:
  flutter-ios-workflow:
    name: Carpool Meter app
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: newtaxikey
    environment:
      groups:
        - ios_signing
      vars:
        APP_STORE_APPLE_ID: 6786974799
        BUNDLE_ID: com.tbmtbw.meter
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Set up keychain
        script: keychain initialize
      - name: Set up signing certificate
        script: |
          printf '%s' "$CM_CERTIFICATE" | base64 --decode > /tmp/distribution.p12
          openssl pkcs12 -in /tmp/distribution.p12 -noout -passin pass:"$CM_CERTIFICATE_PASSWORD"
          keychain add-certificates -c /tmp/distribution.p12 -p "$CM_CERTIFICATE_PASSWORD"
      - name: Fetch signing files
        script: |
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles
      - name: Increment build number
        script: |
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          cd ios
          agvtool new-version -all $(($LATEST_BUILD_NUMBER + 1))
      - name: Build Flutter IPA for distribution
        script: |
          flutter build ios --release --no-codesign
          xcode-project build-ipa --workspace "$CM_BUILD_DIR/ios/Runner.xcworkspace" --scheme "Runner"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - tbmtbw.app@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true